### ISSUE TITLE
[BUG] Nether in Debug/Whitebox mode

### ISSUE THREAD

**Issue by Joegenco** [unicornbloods/BeyondBeliefVanillaReborn#10]
The nether seems to be in a debug mode of some sort? All the surfaces are white.

Minecraft version: 1.14.4

Optifine version: F5

Shader version: BBVR_Rewrite3

Graphics card: 1080Ti

Operating system: W10

Screenshots if any (Visual errors): 
![2020-05-06_17 33 23](https://user-images.githubusercontent.com/33637910/81190016-f464e580-8fbf-11ea-8b8b-23496c57a436.png)

latest.log if any (OpenGL errors):
Actions taken in the log file: Open game, enter world, nether, exit to overworld, enter back to nether, leave the game.
[latest.log](https://github.com/unicornbloods/BeyondBeliefVanillaReborn/files/4587419/latest.log)

**Comment by unicornbloods** [comment]
Fixed in github alpha. Will push to curse this week.
