### ISSUE TITLE
[BUG] Hitting mobs does not make them red

### ISSUE THREAD

**Issue by fr3fou** [unicornbloods/BeyondBeliefVanillaReborn#13]
Minecraft version:

1.15.2

Optifine version:

Pre16

Shader version:

commit: fe303efedf9b5883ad18d44700095a4bd9bf395c

Graphics card:

rx 570

Operating system:

win10

Description of the bug:

hitting the mobs doesn't make them flash red like in vanilla

Screenshots if any (Visual errors):

latest.log if any (OpenGL errors):

**Comment by unicornbloods** [comment]
Thank you for the report,
     I will test this tomorrow that is my setup shader development day, would be nice if you could answer this quick question though.  Did you try 1.14.4 too or only 1.15.2?  It could potentially be an Optifine preview issue just like with custom selection box not working.

**Comment by fr3fou** [comment]
> Thank you for the report,
> I will test this tomorrow that is my setup shader development day, would be nice if you could answer this quick question though. Did you try 1.14.4 too or only 1.15.2? It could potentially be an Optifine preview issue just like with custom selection box not working.

i'll try 1.14.4 and report

**Comment by fr3fou** [comment]
same issue on 1.14.4 with latest optifine HD U F5

**Comment by unicornbloods** [comment]
Fixed.
