### ISSUE TITLE
Noise on the water for "No Texture settings"

### ISSUE THREAD

**Issue by jmarucha** [unicornbloods/BeyondBeliefVanillaReborn#4]
Version: Minecraft 1.15.2 with OptiFine G1pre13 on W10
Hardware: GTX 1060 Mobile

When set up for "No texture" the overworld water starts to look like a plain artifact. This is noticable (but less prominent) when the texture is on, but it is "covered" by texture and less painfull (however changing the alpha of water can make the mess again).
![2020-04-12_17 26 06](https://user-images.githubusercontent.com/8832340/79073100-e71c4a00-7ce4-11ea-8594-c79ec2aaef2e.png)

**Comment by unicornbloods** [comment]
This seems to be part of this issue https://github.com/unicornbloods/BeyondBeliefVanillaReborn/issues/2 since the matID is making that color apply to color apply to clouds as well and it can cause that water issue. I am still trying to find a fix.

**Comment by unicornbloods** [comment]
Is this still an issue?
in latest git
