### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MajsterKyblik** [unicornbloods/BeyondBeliefVanillaReborn#5]
Minecraft version:ANY

Optifine version:ANY

Shader version: Final V1.1

Graphics card: AMD RX580 Sapphire

Operating system: Windows 10 Pro N 1909

Description of the bug: When i load the shaders and quickly look at the the console i see a crash after creating Framebuffer 

Screenshots if any (Visual errors):

![2020 04 16-10 22](https://user-images.githubusercontent.com/63782050/79439111-b97d1c80-7fd4-11ea-9d82-3be303938205.png)

![2020 04 16-10 21](https://user-images.githubusercontent.com/63782050/79439124-be41d080-7fd4-11ea-963b-a4d16fc828ee.png)

![2020 04 16-10 21_01](https://user-images.githubusercontent.com/63782050/79439135-c0a42a80-7fd4-11ea-93ae-a9b6eae9ef74.png)

**Comment by unicornbloods** [comment]
This is the Vanilla reborn github
