### ISSUE TITLE
More settings(I will give more ideas later :D)

### ISSUE THREAD

**Issue by fr0zert** [unicornbloods/BeyondBeliefVanillaReborn#6]
Description:
Can u add setting for enable / disable hand "Depth Of Field"
Images if any:
![2020-04-24_19 04 16](https://user-images.githubusercontent.com/52128237/80233339-001ae880-865f-11ea-9220-d18caa020aef.png)

**Comment by unicornbloods** [comment]
I can look into it!

**Comment by unicornbloods** [comment]
1.15 is bugged but 1.14 works
