### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fr0zert** [unicornbloods/BeyondBeliefVanillaReborn#7]
Minecraft version: look screenshot

Optifine version: look screenshot

Shader version: look screenshot

Graphics card: AMD RX580

Operating system: win10 x64

Description of the bug: white textures in nether

Screenshots if any (Visual errors):
![2020-04-24_19 27 56](https://user-images.githubusercontent.com/52128237/80235386-4faee380-8662-11ea-9b8d-a7a772759afe.png)

latest.log if any (OpenGL errors):
[latest.log](https://github.com/unicornbloods/BeyondBeliefVanillaReborn/files/4530172/latest.log)

**Comment by unicornbloods** [comment]
Thanks for the report!!! It will be fixed in a bit. For some reason my new update made the nether realize it needed some gbuffer programs.
