### ISSUE TITLE
[BUG] Honey blocks visual glitch

### ISSUE THREAD

**Issue by polzol** [unicornbloods/BeyondBeliefVanillaReborn#8]
Minecraft version: 1.15.2

Optifine version: 1.15.2 Pre13

Shader version: 0.0.19.3 and Rewritew3

Graphics card: 2070 Super

Operating system: Windows 10 Pro

Description of the bug: Honey blocks flicker rapidly between their normal color and blue

Screenshots if any (Visual errors):
![2020-04-28_18 58 56](https://user-images.githubusercontent.com/48031025/80515529-64e98200-8982-11ea-8eff-6222cdef4912.png)

latest.log if any (OpenGL errors):

**Comment by JoubaMety** [comment]
_I thought you cannot report issues with 1.15 preview builds, hmm._

**Comment by unicornbloods** [comment]
Lol thanks Jouba but it is a matID issue I believe so I will have to look into that. Probably just need to add honeyblocks to the translucents block ids

**Comment by polzol** [comment]
Thank you unicornbloods, your work is greatly appreciated

**Comment by unicornbloods** [comment]
fixed
