### ISSUE TITLE
[BUG] Stained Glass

### ISSUE THREAD

**Issue by Mercurymoon01** [unicornbloods/BeyondBeliefVanillaReborn#9]
For simplicity sake please use my issue format <3
It will also make it way easier for me to help you with the information asked for.

Minecraft version: 1.15.2

Optifine version: 1.15.2 pre13

Shader version: 0.0.19.3

Graphics card: GTX 1080Ti

Operating system: windows 10

Description of the bug: stained glass without a backdrop is unusable

Screenshots if any (Visual errors):
![2020-05-01_11 17 55](https://user-images.githubusercontent.com/64638553/80799258-4790ff80-8b9e-11ea-9347-a3bca7226da7.png)

latest.log if any (OpenGL errors):

**Comment by unicornbloods** [comment]
Fixed during the rewrite. Thanks for the report!!
